hs.hotkey.bind({ "cmd", "shift" }, "y", function()
	hs.application.open("Firefox Developer Edition.app")
end)
hs.hotkey.bind({ "cmd", "shift" }, "e", function()
	hs.application.open("Google Chrome")
end)
hs.hotkey.bind({ "cmd", "shift" }, "t", function()
	hs.application.open("iterm")
end)
